version: "3"

services:
  client:
    build: ./client/
    expose:
      - "80"
    ports:
      - "80"
    env_file:
      - .env
    environment:
      VIRTUAL_HOST: ${WEBSITE_DOMAINS}
      VIRTUAL_PROTO: http
      VIRTUAL_PORT: 80
      LETSENCRYPT_HOST: ${WEBSITE_DOMAINS}
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
      LETSENCRYPT_SINGLE_DOMAIN_CERTS: "true"
    restart: always

  api:
    build: ./api/
    expose:
      - "80"
    ports:
      - "80"
    env_file:
      - .env
    restart: always
    environment:
      VIRTUAL_HOST: ${API_DOMAINS}
      VIRTUAL_PROTO: http
      VIRTUAL_PORT: 80
      LETSENCRYPT_HOST: ${API_DOMAINS}
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
      LETSENCRYPT_SINGLE_DOMAIN_CERTS: "true"

  nginx-proxy:
    build: ./proxy/
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/vhost.d/:/etc/nginx/vhost.d
      - ./nginx/html/:/usr/share/nginx/html
      - ./nginx/certs/:/etc/nginx/certs
      - /var/run/docker.sock:/tmp/docker.sock:ro
    restart: always
    labels:
      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
    depends_on:
      - client

  letsencrypt-nginx-proxy-companion:
    image: jrcs/letsencrypt-nginx-proxy-companion:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /var/run/docker.sock:/tmp/docker.sock
      - ./nginx/vhost.d/:/etc/nginx/vhost.d
      - ./nginx/html/:/usr/share/nginx/html
      - ./nginx/certs/:/etc/nginx/certs
    depends_on:
      - nginx-proxy
